EATS_BASE_IRI = 'http://eats.artefact.org.nz/psi/'

AUTHORITY_TYPE_IRI = EATS_BASE_IRI + 'authority/'
ADMIN_NAME_TYPE_IRI = EATS_BASE_IRI + 'admin_name/'
AUTHORITY_BASE_URL_IRI = EATS_BASE_IRI + 'authority_base_url/'
ENTITY_TYPE_IRI = EATS_BASE_IRI + 'entity/'
LANGUAGE_CODE_TYPE_IRI = EATS_BASE_IRI + 'language_code/'
LANGUAGE_TYPE_IRI = EATS_BASE_IRI + 'language/'
SCRIPT_CODE_TYPE_IRI = EATS_BASE_IRI + 'script_code/'
SCRIPT_TYPE_IRI = EATS_BASE_IRI + 'script/'
