EATS_BASE_IRI = 'http://eats.artefact.org.nz/psi/'
AUTHORITY_TYPE_IRI = EATS_BASE_IRI + 'authority_type/'
ENTITY_TYPE_IRI = EATS_BASE_IRI + 'entity_type/'
ADMIN_NAME_TYPE_IRI = EATS_BASE_IRI + 'admin_name_type/'
AUTHORITY_BASE_URL_IRI = EATS_BASE_IRI + 'authority_base_url/'
