//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.04.06 at 03:37:39 PM NZST
//


package uk.ac.kcl.cch.eats.eatsml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://eats.artefact.org.nz/ns/eatsml/}name">
 *       &lt;sequence>
 *         &lt;element name="calendars" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="calendar" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="date_periods" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date_period" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="date_types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date_type" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="entity_relationship_types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entity_relationship_type" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="entity_types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entity_type" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="languages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="language" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="name_part_types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name_part_type" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="name_types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name_type" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="scripts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="script" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}id_attribute"/>
 *       &lt;attribute name="eats_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="user_preferred" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "calendars",
    "datePeriods",
    "dateTypes",
    "entityRelationshipTypes",
    "entityTypes",
    "languages",
    "namePartTypes",
    "nameTypes",
    "scripts"
})
@XmlRootElement(name = "authority")
public class Authority
    extends Name
{

    protected Authority.Calendars calendars;
    @XmlElement(name = "date_periods")
    protected Authority.DatePeriods datePeriods;
    @XmlElement(name = "date_types")
    protected Authority.DateTypes dateTypes;
    @XmlElement(name = "entity_relationship_types")
    protected Authority.EntityRelationshipTypes entityRelationshipTypes;
    @XmlElement(name = "entity_types")
    protected Authority.EntityTypes entityTypes;
    protected Authority.Languages languages;
    @XmlElement(name = "name_part_types")
    protected Authority.NamePartTypes namePartTypes;
    @XmlElement(name = "name_types")
    protected Authority.NameTypes nameTypes;
    protected Authority.Scripts scripts;
    @XmlAttribute(name = "eats_id")
    @XmlSchemaType(name = "anySimpleType")
    protected String eatsId;
    @XmlAttribute(name = "user_preferred")
    protected Boolean userPreferred = false;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the calendars property.
     *
     * @return
     *     possible object is
     *     {@link Authority.Calendars }
     *
     */
    public Authority.Calendars getCalendars() {
        return calendars;
    }

    /**
     * Sets the value of the calendars property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.Calendars }
     *
     */
    public void setCalendars(Authority.Calendars value) {
        this.calendars = value;
    }

    /**
     * Gets the value of the datePeriods property.
     *
     * @return
     *     possible object is
     *     {@link Authority.DatePeriods }
     *
     */
    public Authority.DatePeriods getDatePeriods() {
        return datePeriods;
    }

    /**
     * Sets the value of the datePeriods property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.DatePeriods }
     *
     */
    public void setDatePeriods(Authority.DatePeriods value) {
        this.datePeriods = value;
    }

    /**
     * Gets the value of the dateTypes property.
     *
     * @return
     *     possible object is
     *     {@link Authority.DateTypes }
     *
     */
    public Authority.DateTypes getDateTypes() {
        return dateTypes;
    }

    /**
     * Sets the value of the dateTypes property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.DateTypes }
     *
     */
    public void setDateTypes(Authority.DateTypes value) {
        this.dateTypes = value;
    }

    /**
     * Gets the value of the entityRelationshipTypes property.
     *
     * @return
     *     possible object is
     *     {@link Authority.EntityRelationshipTypes }
     *
     */
    public Authority.EntityRelationshipTypes getEntityRelationshipTypes() {
        return entityRelationshipTypes;
    }

    /**
     * Sets the value of the entityRelationshipTypes property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.EntityRelationshipTypes }
     *
     */
    public void setEntityRelationshipTypes(Authority.EntityRelationshipTypes value) {
        this.entityRelationshipTypes = value;
    }

    /**
     * Gets the value of the entityTypes property.
     *
     * @return
     *     possible object is
     *     {@link Authority.EntityTypes }
     *
     */
    public Authority.EntityTypes getEntityTypes() {
        return entityTypes;
    }

    /**
     * Sets the value of the entityTypes property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.EntityTypes }
     *
     */
    public void setEntityTypes(Authority.EntityTypes value) {
        this.entityTypes = value;
    }

    /**
     * Gets the value of the languages property.
     *
     * @return
     *     possible object is
     *     {@link Authority.Languages }
     *
     */
    public Authority.Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.Languages }
     *
     */
    public void setLanguages(Authority.Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the namePartTypes property.
     *
     * @return
     *     possible object is
     *     {@link Authority.NamePartTypes }
     *
     */
    public Authority.NamePartTypes getNamePartTypes() {
        return namePartTypes;
    }

    /**
     * Sets the value of the namePartTypes property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.NamePartTypes }
     *
     */
    public void setNamePartTypes(Authority.NamePartTypes value) {
        this.namePartTypes = value;
    }

    /**
     * Gets the value of the nameTypes property.
     *
     * @return
     *     possible object is
     *     {@link Authority.NameTypes }
     *
     */
    public Authority.NameTypes getNameTypes() {
        return nameTypes;
    }

    /**
     * Sets the value of the nameTypes property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.NameTypes }
     *
     */
    public void setNameTypes(Authority.NameTypes value) {
        this.nameTypes = value;
    }

    /**
     * Gets the value of the scripts property.
     *
     * @return
     *     possible object is
     *     {@link Authority.Scripts }
     *
     */
    public Authority.Scripts getScripts() {
        return scripts;
    }

    /**
     * Sets the value of the scripts property.
     *
     * @param value
     *     allowed object is
     *     {@link Authority.Scripts }
     *
     */
    public void setScripts(Authority.Scripts value) {
        this.scripts = value;
    }

    /**
     * Gets the value of the eatsId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEatsId() {
        return eatsId;
    }

    /**
     * Sets the value of the eatsId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEatsId(String value) {
        this.eatsId = value;
    }

    /**
     * Gets the value of the userPreferred property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isUserPreferred() {
        return userPreferred;
    }

    /**
     * Sets the value of the userPreferred property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setUserPreferred(Boolean value) {
        this.userPreferred = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="calendar" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "calendar"
    })
    public static class Calendars {

        @XmlElement(required = true)
        protected List<Authority.Calendars.Calendar> calendar;

        /**
         * Gets the value of the calendar property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the calendar property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCalendar().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.Calendars.Calendar }
         *
         *
         */
        public List<Authority.Calendars.Calendar> getCalendar() {
            if (calendar == null) {
                calendar = new ArrayList<Authority.Calendars.Calendar>();
            }
            return this.calendar;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Calendar {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date_period" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datePeriod"
    })
    public static class DatePeriods {

        @XmlElement(name = "date_period", required = true)
        protected List<Authority.DatePeriods.DatePeriod> datePeriod;

        /**
         * Gets the value of the datePeriod property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the datePeriod property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDatePeriod().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.DatePeriods.DatePeriod }
         *
         *
         */
        public List<Authority.DatePeriods.DatePeriod> getDatePeriod() {
            if (datePeriod == null) {
                datePeriod = new ArrayList<Authority.DatePeriods.DatePeriod>();
            }
            return this.datePeriod;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DatePeriod {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date_type" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateType"
    })
    public static class DateTypes {

        @XmlElement(name = "date_type", required = true)
        protected List<Authority.DateTypes.DateType> dateType;

        /**
         * Gets the value of the dateType property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dateType property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDateType().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.DateTypes.DateType }
         *
         *
         */
        public List<Authority.DateTypes.DateType> getDateType() {
            if (dateType == null) {
                dateType = new ArrayList<Authority.DateTypes.DateType>();
            }
            return this.dateType;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DateType {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entity_relationship_type" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entityRelationshipType"
    })
    public static class EntityRelationshipTypes {

        @XmlElement(name = "entity_relationship_type", required = true)
        protected List<Authority.EntityRelationshipTypes.EntityRelationshipType> entityRelationshipType;

        /**
         * Gets the value of the entityRelationshipType property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entityRelationshipType property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntityRelationshipType().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.EntityRelationshipTypes.EntityRelationshipType }
         *
         *
         */
        public List<Authority.EntityRelationshipTypes.EntityRelationshipType> getEntityRelationshipType() {
            if (entityRelationshipType == null) {
                entityRelationshipType = new ArrayList<Authority.EntityRelationshipTypes.EntityRelationshipType>();
            }
            return this.entityRelationshipType;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EntityRelationshipType {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entity_type" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entityType"
    })
    public static class EntityTypes {

        @XmlElement(name = "entity_type", required = true)
        protected List<Authority.EntityTypes.EntityType> entityType;

        /**
         * Gets the value of the entityType property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entityType property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntityType().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.EntityTypes.EntityType }
         *
         *
         */
        public List<Authority.EntityTypes.EntityType> getEntityType() {
            if (entityType == null) {
                entityType = new ArrayList<Authority.EntityTypes.EntityType>();
            }
            return this.entityType;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EntityType {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="language" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "language"
    })
    public static class Languages {

        @XmlElement(required = true)
        protected List<Authority.Languages.Language> language;

        /**
         * Gets the value of the language property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.Languages.Language }
         *
         *
         */
        public List<Authority.Languages.Language> getLanguage() {
            if (language == null) {
                language = new ArrayList<Authority.Languages.Language>();
            }
            return this.language;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Language {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name_part_type" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "namePartType"
    })
    public static class NamePartTypes {

        @XmlElement(name = "name_part_type", required = true)
        protected List<Authority.NamePartTypes.NamePartType> namePartType;

        /**
         * Gets the value of the namePartType property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the namePartType property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNamePartType().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.NamePartTypes.NamePartType }
         *
         *
         */
        public List<Authority.NamePartTypes.NamePartType> getNamePartType() {
            if (namePartType == null) {
                namePartType = new ArrayList<Authority.NamePartTypes.NamePartType>();
            }
            return this.namePartType;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class NamePartType {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name_type" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameType"
    })
    public static class NameTypes {

        @XmlElement(name = "name_type", required = true)
        protected List<Authority.NameTypes.NameType> nameType;

        /**
         * Gets the value of the nameType property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nameType property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNameType().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.NameTypes.NameType }
         *
         *
         */
        public List<Authority.NameTypes.NameType> getNameType() {
            if (nameType == null) {
                nameType = new ArrayList<Authority.NameTypes.NameType>();
            }
            return this.nameType;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class NameType {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="script" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "script"
    })
    public static class Scripts {

        @XmlElement(required = true)
        protected List<Authority.Scripts.Script> script;

        /**
         * Gets the value of the script property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the script property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScript().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Authority.Scripts.Script }
         *
         *
         */
        public List<Authority.Scripts.Script> getScript() {
            if (script == null) {
                script = new ArrayList<Authority.Scripts.Script>();
            }
            return this.script;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}ref_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Script {

            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the ref property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }

}
