//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.06 at 03:37:39 PM NZST 
//


package uk.ac.kcl.cch.eats.eatsml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}authorities"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}calendars"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}date_periods"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}date_types"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}entity_relationship_types"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}entity_types"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}languages"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}name_part_types"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}name_types"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}scripts"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}entities"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authorities",
    "calendars",
    "datePeriods",
    "dateTypes",
    "entityRelationshipTypes",
    "entityTypes",
    "languages",
    "namePartTypes",
    "nameTypes",
    "scripts",
    "entities"
})
@XmlRootElement(name = "collection")
public class Collection {

    protected Authorities authorities;
    protected Calendars calendars;
    @XmlElement(name = "date_periods")
    protected DatePeriods datePeriods;
    @XmlElement(name = "date_types")
    protected DateTypes dateTypes;
    @XmlElement(name = "entity_relationship_types")
    protected EntityRelationshipTypes entityRelationshipTypes;
    @XmlElement(name = "entity_types")
    protected Collection.EntityTypes entityTypes;
    protected Languages languages;
    @XmlElement(name = "name_part_types")
    protected NamePartTypes namePartTypes;
    @XmlElement(name = "name_types")
    protected NameTypes nameTypes;
    protected Scripts scripts;
    protected Entities entities;

    /**
     * Gets the value of the authorities property.
     * 
     * @return
     *     possible object is
     *     {@link Authorities }
     *     
     */
    public Authorities getAuthorities() {
        return authorities;
    }

    /**
     * Sets the value of the authorities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authorities }
     *     
     */
    public void setAuthorities(Authorities value) {
        this.authorities = value;
    }

    /**
     * Gets the value of the calendars property.
     * 
     * @return
     *     possible object is
     *     {@link Calendars }
     *     
     */
    public Calendars getCalendars() {
        return calendars;
    }

    /**
     * Sets the value of the calendars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendars }
     *     
     */
    public void setCalendars(Calendars value) {
        this.calendars = value;
    }

    /**
     * Gets the value of the datePeriods property.
     * 
     * @return
     *     possible object is
     *     {@link DatePeriods }
     *     
     */
    public DatePeriods getDatePeriods() {
        return datePeriods;
    }

    /**
     * Sets the value of the datePeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatePeriods }
     *     
     */
    public void setDatePeriods(DatePeriods value) {
        this.datePeriods = value;
    }

    /**
     * Gets the value of the dateTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DateTypes }
     *     
     */
    public DateTypes getDateTypes() {
        return dateTypes;
    }

    /**
     * Sets the value of the dateTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTypes }
     *     
     */
    public void setDateTypes(DateTypes value) {
        this.dateTypes = value;
    }

    /**
     * Gets the value of the entityRelationshipTypes property.
     * 
     * @return
     *     possible object is
     *     {@link EntityRelationshipTypes }
     *     
     */
    public EntityRelationshipTypes getEntityRelationshipTypes() {
        return entityRelationshipTypes;
    }

    /**
     * Sets the value of the entityRelationshipTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityRelationshipTypes }
     *     
     */
    public void setEntityRelationshipTypes(EntityRelationshipTypes value) {
        this.entityRelationshipTypes = value;
    }

    /**
     * Gets the value of the entityTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Collection.EntityTypes }
     *     
     */
    public Collection.EntityTypes getEntityTypes() {
        return entityTypes;
    }

    /**
     * Sets the value of the entityTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Collection.EntityTypes }
     *     
     */
    public void setEntityTypes(Collection.EntityTypes value) {
        this.entityTypes = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link Languages }
     *     
     */
    public Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languages }
     *     
     */
    public void setLanguages(Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the namePartTypes property.
     * 
     * @return
     *     possible object is
     *     {@link NamePartTypes }
     *     
     */
    public NamePartTypes getNamePartTypes() {
        return namePartTypes;
    }

    /**
     * Sets the value of the namePartTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamePartTypes }
     *     
     */
    public void setNamePartTypes(NamePartTypes value) {
        this.namePartTypes = value;
    }

    /**
     * Gets the value of the nameTypes property.
     * 
     * @return
     *     possible object is
     *     {@link NameTypes }
     *     
     */
    public NameTypes getNameTypes() {
        return nameTypes;
    }

    /**
     * Sets the value of the nameTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameTypes }
     *     
     */
    public void setNameTypes(NameTypes value) {
        this.nameTypes = value;
    }

    /**
     * Gets the value of the scripts property.
     * 
     * @return
     *     possible object is
     *     {@link Scripts }
     *     
     */
    public Scripts getScripts() {
        return scripts;
    }

    /**
     * Sets the value of the scripts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scripts }
     *     
     */
    public void setScripts(Scripts value) {
        this.scripts = value;
    }

    /**
     * Gets the value of the entities property.
     * 
     * @return
     *     possible object is
     *     {@link Entities }
     *     
     */
    public Entities getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entities }
     *     
     */
    public void setEntities(Entities value) {
        this.entities = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entity_type" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://eats.artefact.org.nz/ns/eatsml/}name">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}id_attribute"/>
     *                 &lt;attribute name="eats_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entityType"
    })
    public static class EntityTypes {

        @XmlElement(name = "entity_type", required = true)
        protected List<Collection.EntityTypes.EntityType> entityType;

        /**
         * Gets the value of the entityType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entityType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntityType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Collection.EntityTypes.EntityType }
         * 
         * 
         */
        public List<Collection.EntityTypes.EntityType> getEntityType() {
            if (entityType == null) {
                entityType = new ArrayList<Collection.EntityTypes.EntityType>();
            }
            return this.entityType;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://eats.artefact.org.nz/ns/eatsml/}name">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}id_attribute"/>
         *       &lt;attribute name="eats_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EntityType
            extends Name
        {

            @XmlAttribute(name = "eats_id")
            @XmlSchemaType(name = "anySimpleType")
            protected String eatsId;
            @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;

            /**
             * Gets the value of the eatsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEatsId() {
                return eatsId;
            }

            /**
             * Sets the value of the eatsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEatsId(String value) {
                this.eatsId = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
