//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.06 at 03:37:39 PM NZST 
//


package uk.ac.kcl.cch.eats.eatsml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}assembled_form"/>
 *         &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}date_parts"/>
 *       &lt;/sequence>
 *       &lt;attribute name="date_period" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assembledForm",
    "dateParts"
})
@XmlRootElement(name = "date")
public class Date {

    @XmlElement(name = "assembled_form", required = true)
    protected String assembledForm;
    @XmlElement(name = "date_parts", required = true)
    protected DateParts dateParts;
    @XmlAttribute(name = "date_period", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object datePeriod;

    /**
     * Gets the value of the assembledForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssembledForm() {
        return assembledForm;
    }

    /**
     * Sets the value of the assembledForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssembledForm(String value) {
        this.assembledForm = value;
    }

    /**
     * Gets the value of the dateParts property.
     * 
     * @return
     *     possible object is
     *     {@link DateParts }
     *     
     */
    public DateParts getDateParts() {
        return dateParts;
    }

    /**
     * Sets the value of the dateParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateParts }
     *     
     */
    public void setDateParts(DateParts value) {
        this.dateParts = value;
    }

    /**
     * Gets the value of the datePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDatePeriod() {
        return datePeriod;
    }

    /**
     * Sets the value of the datePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDatePeriod(Object value) {
        this.datePeriod = value;
    }

}
