//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.06 at 03:37:39 PM NZST 
//


package uk.ac.kcl.cch.eats.eatsml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}entity_relationship_assertions"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}entity_type_assertions"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}existence_assertions"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}name_assertions"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}note_assertions"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}subject_identifier_assertions"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}id_attribute"/>
 *       &lt;attribute name="eats_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="related_entity" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityRelationships",
    "entityTypes",
    "existences",
    "names",
    "notes",
    "subjectIdentifiers"
})
@XmlRootElement(name = "entity")
public class Entity {

    @XmlElement(name = "entity_relationships")
    protected EntityRelationships entityRelationships;
    @XmlElement(name = "entity_types")
    protected Entity.EntityTypes entityTypes;
    protected Existences existences;
    protected Names names;
    protected Notes notes;
    @XmlElement(name = "subject_identifiers")
    protected SubjectIdentifiers subjectIdentifiers;
    @XmlAttribute(name = "eats_id")
    @XmlSchemaType(name = "anySimpleType")
    protected String eatsId;
    @XmlAttribute(name = "related_entity")
    protected Boolean relatedEntity;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String url;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the entityRelationships property.
     * 
     * @return
     *     possible object is
     *     {@link EntityRelationships }
     *     
     */
    public EntityRelationships getEntityRelationships() {
        return entityRelationships;
    }

    /**
     * Sets the value of the entityRelationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityRelationships }
     *     
     */
    public void setEntityRelationships(EntityRelationships value) {
        this.entityRelationships = value;
    }

    /**
     * Gets the value of the entityTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Entity.EntityTypes }
     *     
     */
    public Entity.EntityTypes getEntityTypes() {
        return entityTypes;
    }

    /**
     * Sets the value of the entityTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entity.EntityTypes }
     *     
     */
    public void setEntityTypes(Entity.EntityTypes value) {
        this.entityTypes = value;
    }

    /**
     * Gets the value of the existences property.
     * 
     * @return
     *     possible object is
     *     {@link Existences }
     *     
     */
    public Existences getExistences() {
        return existences;
    }

    /**
     * Sets the value of the existences property.
     * 
     * @param value
     *     allowed object is
     *     {@link Existences }
     *     
     */
    public void setExistences(Existences value) {
        this.existences = value;
    }

    /**
     * Gets the value of the names property.
     * 
     * @return
     *     possible object is
     *     {@link Names }
     *     
     */
    public Names getNames() {
        return names;
    }

    /**
     * Sets the value of the names property.
     * 
     * @param value
     *     allowed object is
     *     {@link Names }
     *     
     */
    public void setNames(Names value) {
        this.names = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the subjectIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectIdentifiers }
     *     
     */
    public SubjectIdentifiers getSubjectIdentifiers() {
        return subjectIdentifiers;
    }

    /**
     * Sets the value of the subjectIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectIdentifiers }
     *     
     */
    public void setSubjectIdentifiers(SubjectIdentifiers value) {
        this.subjectIdentifiers = value;
    }

    /**
     * Gets the value of the eatsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEatsId() {
        return eatsId;
    }

    /**
     * Sets the value of the eatsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEatsId(String value) {
        this.eatsId = value;
    }

    /**
     * Gets the value of the relatedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRelatedEntity() {
        return relatedEntity;
    }

    /**
     * Sets the value of the relatedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRelatedEntity(Boolean value) {
        this.relatedEntity = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entity_type" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}dates"/>
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}authority_attribute"/>
     *                 &lt;attribute name="eats_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="entity_type" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entityType"
    })
    public static class EntityTypes {

        @XmlElement(name = "entity_type", required = true)
        protected List<Entity.EntityTypes.EntityType> entityType;

        /**
         * Gets the value of the entityType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entityType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntityType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Entity.EntityTypes.EntityType }
         * 
         * 
         */
        public List<Entity.EntityTypes.EntityType> getEntityType() {
            if (entityType == null) {
                entityType = new ArrayList<Entity.EntityTypes.EntityType>();
            }
            return this.entityType;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}dates"/>
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}authority_attribute"/>
         *       &lt;attribute name="eats_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="entity_type" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dates"
        })
        public static class EntityType {

            protected Dates dates;
            @XmlAttribute(name = "eats_id")
            @XmlSchemaType(name = "anySimpleType")
            protected String eatsId;
            @XmlAttribute(name = "entity_type", required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object entityType;
            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object authority;

            /**
             * Gets the value of the dates property.
             * 
             * @return
             *     possible object is
             *     {@link Dates }
             *     
             */
            public Dates getDates() {
                return dates;
            }

            /**
             * Sets the value of the dates property.
             * 
             * @param value
             *     allowed object is
             *     {@link Dates }
             *     
             */
            public void setDates(Dates value) {
                this.dates = value;
            }

            /**
             * Gets the value of the eatsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEatsId() {
                return eatsId;
            }

            /**
             * Sets the value of the eatsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEatsId(String value) {
                this.eatsId = value;
            }

            /**
             * Gets the value of the entityType property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getEntityType() {
                return entityType;
            }

            /**
             * Sets the value of the entityType property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setEntityType(Object value) {
                this.entityType = value;
            }

            /**
             * Gets the value of the authority property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getAuthority() {
                return authority;
            }

            /**
             * Sets the value of the authority property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setAuthority(Object value) {
                this.authority = value;
            }

        }

    }

}
