//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.06 at 03:37:39 PM NZST 
//


package uk.ac.kcl.cch.eats.eatsml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for name complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="name">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}name"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "name", propOrder = {
    "name"
})
@XmlSeeAlso({
    uk.ac.kcl.cch.eats.eatsml.NamePartTypes.NamePartType.class,
    uk.ac.kcl.cch.eats.eatsml.Calendars.Calendar.class,
    uk.ac.kcl.cch.eats.eatsml.DatePeriods.DatePeriod.class,
    uk.ac.kcl.cch.eats.eatsml.DateTypes.DateType.class,
    uk.ac.kcl.cch.eats.eatsml.EntityRelationshipTypes.EntityRelationshipType.class,
    uk.ac.kcl.cch.eats.eatsml.Collection.EntityTypes.EntityType.class,
    uk.ac.kcl.cch.eats.eatsml.Languages.Language.class,
    uk.ac.kcl.cch.eats.eatsml.NameTypes.NameType.class,
    uk.ac.kcl.cch.eats.eatsml.Scripts.Script.class,
    Authority.class
})
public class Name {

    @XmlElement(required = true)
    protected String name;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
