//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 10:13:18 AM NZDT 
//


package nz.org.artefact.eats.ns.eatsml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}assembled_form"/>
 *         &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}date_parts"/>
 *         &lt;group ref="{http://eats.artefact.org.nz/ns/eatsml/}non_assertion_notes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="date_period" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assembledForm",
    "dateParts",
    "notes"
})
@XmlRootElement(name = "date")
public class Date {

    @XmlElement(name = "assembled_form", required = true)
    protected String assembledForm;
    @XmlElement(name = "date_parts", required = true)
    protected DateParts dateParts;
    protected Date.Notes notes;
    @XmlAttribute(name = "date_period", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object datePeriod;

    /**
     * Gets the value of the assembledForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssembledForm() {
        return assembledForm;
    }

    /**
     * Sets the value of the assembledForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssembledForm(String value) {
        this.assembledForm = value;
    }

    /**
     * Gets the value of the dateParts property.
     * 
     * @return
     *     possible object is
     *     {@link DateParts }
     *     
     */
    public DateParts getDateParts() {
        return dateParts;
    }

    /**
     * Sets the value of the dateParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateParts }
     *     
     */
    public void setDateParts(DateParts value) {
        this.dateParts = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Date.Notes }
     *     
     */
    public Date.Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date.Notes }
     *     
     */
    public void setNotes(Date.Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the datePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDatePeriod() {
        return datePeriod;
    }

    /**
     * Sets the value of the datePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDatePeriod(Object value) {
        this.datePeriod = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="note" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}is_note_internal_attribute"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "note"
    })
    public static class Notes {

        @XmlElement(required = true)
        protected List<Date.Notes.Note> note;

        /**
         * Gets the value of the note property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the note property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Date.Notes.Note }
         * 
         * 
         */
        public List<Date.Notes.Note> getNote() {
            if (note == null) {
                note = new ArrayList<Date.Notes.Note>();
            }
            return this.note;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}is_note_internal_attribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Note {

            @XmlValue
            protected String content;
            @XmlAttribute(name = "is_internal", required = true)
            protected boolean isInternal;

            /**
             * Gets the value of the content property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContent() {
                return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContent(String value) {
                this.content = value;
            }

            /**
             * Gets the value of the isInternal property.
             * 
             */
            public boolean isIsInternal() {
                return isInternal;
            }

            /**
             * Sets the value of the isInternal property.
             * 
             */
            public void setIsInternal(boolean value) {
                this.isInternal = value;
            }

        }

    }

}
