//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 10:13:18 AM NZDT 
//


package nz.org.artefact.eats.ns.eatsml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}script_attribute"/>
 *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}language_attribute"/>
 *       &lt;attribute name="name_part_type" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "name_part")
public class NamePart {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "name_part_type", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object namePartType;
    @XmlAttribute(name = "script", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object script;
    @XmlAttribute(name = "language", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object language;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the namePartType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNamePartType() {
        return namePartType;
    }

    /**
     * Sets the value of the namePartType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNamePartType(Object value) {
        this.namePartType = value;
    }

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setScript(Object value) {
        this.script = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLanguage(Object value) {
        this.language = value;
    }

}
