//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 10:13:18 AM NZDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eats.artefact.org.nz/ns/eatsml/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nz.org.artefact.eats.ns.eatsml;
