//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 10:13:18 AM NZDT 
//


package nz.org.artefact.eats.ns.eatsml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="script" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://eats.artefact.org.nz/ns/eatsml/}name">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}code"/>
 *                   &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}separator"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}id_attribute"/>
 *                 &lt;attribute name="eats_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="user_preferred" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "script"
})
@XmlRootElement(name = "scripts")
public class Scripts {

    @XmlElement(required = true)
    protected List<Scripts.Script> script;

    /**
     * Gets the value of the script property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the script property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScript().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Scripts.Script }
     * 
     * 
     */
    public List<Scripts.Script> getScript() {
        if (script == null) {
            script = new ArrayList<Scripts.Script>();
        }
        return this.script;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://eats.artefact.org.nz/ns/eatsml/}name">
     *       &lt;sequence>
     *         &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}code"/>
     *         &lt;element ref="{http://eats.artefact.org.nz/ns/eatsml/}separator"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://eats.artefact.org.nz/ns/eatsml/}id_attribute"/>
     *       &lt;attribute name="eats_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="user_preferred" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "separator"
    })
    public static class Script
        extends Name
    {

        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        protected String separator;
        @XmlAttribute(name = "eats_id")
        @XmlSchemaType(name = "anySimpleType")
        protected String eatsId;
        @XmlAttribute(name = "user_preferred")
        protected Boolean userPreferred;
        @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the separator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeparator() {
            return separator;
        }

        /**
         * Sets the value of the separator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeparator(String value) {
            this.separator = value;
        }

        /**
         * Gets the value of the eatsId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEatsId() {
            return eatsId;
        }

        /**
         * Sets the value of the eatsId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEatsId(String value) {
            this.eatsId = value;
        }

        /**
         * Gets the value of the userPreferred property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isUserPreferred() {
            return userPreferred;
        }

        /**
         * Sets the value of the userPreferred property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUserPreferred(Boolean value) {
            this.userPreferred = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
