from authority_tests import *
from calendar_tests import *
from date_period_tests import *
from date_tests import *
from date_type_tests import *
from eats_topic_map_tests import *
from entity_relationship_tests import *
from entity_relationship_type_tests import *
from entity_tests import *
from entity_type_tests import *
from entity_type_type_tests import *
from language_tests import *
from name_part_tests import *
from name_part_type_tests import *
from name_tests import *
from name_type_tests import *
from note_tests import *
from script_tests import *
from subject_identifier_tests import *
from user_tests import *
