from authority_tests import *
from date_tests import *
from eats_topic_map_tests import *
from entity_relationship_tests import *
from entity_relationship_type_tests import *
from entity_type_tests import *
from language_tests import *
from name_part_tests import *
from name_tests import *
from note_tests import *
from script_tests import *
from user_tests import *
