from administration_panel_tests import *
from authority_tests import *
from calendar_tests import *
from date_add_tests import *
from date_change_tests import *
from date_period_tests import *
from date_type_tests import *
from entity_add_tests import *
from entity_change_tests import *
from entity_relationship_type_tests import *
from entity_type_tests import *
from language_tests import *
from name_part_type_tests import *
from name_type_tests import *
from script_tests import *
