from .test_administration_panel import *
from .test_authority import *
from .test_calendar import *
from .test_date_add import *
from .test_date_change import *
from .test_date_period import *
from .test_date_type import *
from .test_eatsml_import import *
from .test_entity_add import *
from .test_entity_change import *
from .test_entity_display import *
from .test_entity_delete import *
from .test_entity_merge import *
from .test_entity_relationship_type import *
from .test_entity_type import *
from .test_language import *
from .test_name_part_type import *
from .test_name_type import *
from .test_script import *
