/*
 * LookupView.java
 *
 * Created on Sep 14, 2010, 4:03:27 PM
 */
package uk.ac.kcl.cch.eats.lookup;

import javax.swing.JTextPane;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.JToolBar.Separator;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvieira
 */
public class LookupView extends javax.swing.JDialog {

    /** Creates new form LookupView */
    public LookupView() {
        initComponents();
    }

    /**
     * @param owner
     * @param title
     * @param modal
     */
    public LookupView(Frame owner, String title, boolean modal) {
        super(owner, title, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbarPanel = new JPanel();
        toolbar = new JToolBar();
        preferencesButton = new JButton();
        jSeparator = new Separator();
        editButton = new JButton();
        jSeparator1 = new Separator();
        refsButton = new JButton();
        splitPane = new JSplitPane();
        formPane = new JScrollPane();
        formPanel = new JPanel();
        dynFormPanel = new JPanel();
        staticFormPanel = new JPanel();
        authorityLabel = new JLabel();
        scriptLabel = new JLabel();
        languageCombo = new JComboBox();
        entityTypeLabel = new JLabel();
        languageLabel = new JLabel();
        authorityText = new JTextField();
        entityTypeCombo = new JComboBox();
        nameTypeLabel = new JLabel();
        scriptCombo = new JComboBox();
        displayNameLabel = new JLabel();
        nameTypeCombo = new JComboBox();
        displayNameText = new JTextField();
        resultsPane = new JScrollPane();
        resultsSplitPane = new JSplitPane();
        resultsScrollPane = new JScrollPane();
        resultsTable = new JTable();
        detailsScrollPane = new JScrollPane();
        detailsTextPane = new JTextPane();
        bottomPanel = new JPanel();
        cancelButton = new JButton();
        newButton = new JButton();
        findButton = new JButton();
        statusLabel = new JLabel();

        setTitle("Look up name");
        setAlwaysOnTop(true);
        setMinimumSize(new Dimension(1000, 600));
        setName("frame"); // NOI18N

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        preferencesButton.setText("Preferences");
        preferencesButton.setFocusable(false);
        preferencesButton.setHorizontalTextPosition(SwingConstants.CENTER);
        preferencesButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolbar.add(preferencesButton);
        toolbar.add(jSeparator);

        editButton.setText("Edit Entity");
        editButton.setFocusable(false);
        editButton.setHorizontalTextPosition(SwingConstants.CENTER);
        editButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolbar.add(editButton);
        toolbar.add(jSeparator1);

        refsButton.setText("Show References");
        refsButton.setFocusable(false);
        refsButton.setHorizontalTextPosition(SwingConstants.CENTER);
        refsButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolbar.add(refsButton);

        GroupLayout toolbarPanelLayout = new GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(toolbarPanelLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(toolbar, GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        toolbarPanelLayout.setVerticalGroup(toolbarPanelLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(toolbar, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        );

        splitPane.setDividerLocation(500);

        formPane.setMinimumSize(new Dimension(500, 400));

        dynFormPanel.setBorder(BorderFactory.createTitledBorder("Name part types"));

        GroupLayout dynFormPanelLayout = new GroupLayout(dynFormPanel);
        dynFormPanel.setLayout(dynFormPanelLayout);
        dynFormPanelLayout.setHorizontalGroup(dynFormPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        dynFormPanelLayout.setVerticalGroup(dynFormPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        authorityLabel.setText("Authority:");

        scriptLabel.setText("Script:");

        entityTypeLabel.setText("Entity type:");

        languageLabel.setText("Language:");

        authorityText.setEditable(false);
        authorityText.setForeground(UIManager.getDefaults().getColor("TextField.inactiveForeground"));

        nameTypeLabel.setText("Name type:");

        displayNameLabel.setText("Display name:");

        GroupLayout staticFormPanelLayout = new GroupLayout(staticFormPanel);
        staticFormPanel.setLayout(staticFormPanelLayout);
        staticFormPanelLayout.setHorizontalGroup(staticFormPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(staticFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(staticFormPanelLayout.createSequentialGroup()
                        .addComponent(nameTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nameTypeCombo, 0, 366, Short.MAX_VALUE))
                    .addGroup(staticFormPanelLayout.createSequentialGroup()
                        .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.LEADING)
                            .addComponent(entityTypeLabel)
                            .addComponent(languageLabel)
                            .addComponent(scriptLabel))
                        .addGap(18, 18, 18)
                        .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.LEADING)
                            .addComponent(entityTypeCombo, 0, 366, Short.MAX_VALUE)
                            .addComponent(languageCombo, 0, 366, Short.MAX_VALUE)
                            .addComponent(scriptCombo, 0, 366, Short.MAX_VALUE)))
                    .addGroup(staticFormPanelLayout.createSequentialGroup()
                        .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.LEADING)
                            .addComponent(displayNameLabel)
                            .addComponent(authorityLabel))
                        .addGap(2, 2, 2)
                        .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.LEADING)
                            .addComponent(displayNameText, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(authorityText, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        staticFormPanelLayout.setVerticalGroup(staticFormPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(staticFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(authorityLabel)
                    .addComponent(authorityText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(displayNameLabel)
                    .addComponent(displayNameText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(entityTypeLabel)
                    .addComponent(entityTypeCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(languageLabel)
                    .addComponent(languageCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(scriptLabel)
                    .addComponent(scriptCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(staticFormPanelLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(nameTypeCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTypeLabel))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout formPanelLayout = new GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(formPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGroup(formPanelLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(staticFormPanel, Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dynFormPanel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formPanelLayout.setVerticalGroup(formPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addComponent(staticFormPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(dynFormPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        formPane.setViewportView(formPanel);

        splitPane.setLeftComponent(formPane);

        resultsSplitPane.setBorder(null);
        resultsSplitPane.setDividerLocation(300);
        resultsSplitPane.setOrientation(JSplitPane.VERTICAL_SPLIT);

        resultsTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entity", "Entity details", "Entity type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultsScrollPane.setViewportView(resultsTable);
        if (resultsTable.getColumnModel().getColumnCount() > 0) {
            resultsTable.getColumnModel().getColumn(0).setResizable(false);
        }

        resultsSplitPane.setTopComponent(resultsScrollPane);

        detailsTextPane.setEditable(false);
        detailsTextPane.setContentType("text/html"); // NOI18N
        detailsScrollPane.setViewportView(detailsTextPane);

        resultsSplitPane.setRightComponent(detailsScrollPane);

        resultsPane.setViewportView(resultsSplitPane);

        splitPane.setRightComponent(resultsPane);

        bottomPanel.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));

        cancelButton.setText("Cancel");

        newButton.setText("New");

        findButton.setText("Find");

        statusLabel.setText("status");

        GroupLayout bottomPanelLayout = new GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(bottomPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addComponent(statusLabel)
                .addContainerGap(716, Short.MAX_VALUE))
            .addGroup(Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(497, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(newButton)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(findButton))
        );

        bottomPanelLayout.linkSize(SwingConstants.HORIZONTAL, new Component[] {cancelButton, findButton, newButton});

        bottomPanelLayout.setVerticalGroup(bottomPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(bottomPanelLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(findButton)
                    .addComponent(newButton)
                    .addComponent(cancelButton))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(statusLabel))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addComponent(toolbarPanel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(bottomPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(splitPane, GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbarPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(splitPane, GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(bottomPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LookupView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JLabel authorityLabel;
    public JTextField authorityText;
    public JPanel bottomPanel;
    public JButton cancelButton;
    public JScrollPane detailsScrollPane;
    public JTextPane detailsTextPane;
    public JLabel displayNameLabel;
    public JTextField displayNameText;
    public JPanel dynFormPanel;
    public JButton editButton;
    public JComboBox entityTypeCombo;
    public JLabel entityTypeLabel;
    public JButton findButton;
    public JScrollPane formPane;
    public JPanel formPanel;
    public Separator jSeparator;
    public Separator jSeparator1;
    public JComboBox languageCombo;
    public JLabel languageLabel;
    public JComboBox nameTypeCombo;
    public JLabel nameTypeLabel;
    public JButton newButton;
    public JButton preferencesButton;
    public JButton refsButton;
    public JScrollPane resultsPane;
    public JScrollPane resultsScrollPane;
    public JSplitPane resultsSplitPane;
    public JTable resultsTable;
    public JComboBox scriptCombo;
    public JLabel scriptLabel;
    public JSplitPane splitPane;
    public JPanel staticFormPanel;
    public JLabel statusLabel;
    public JToolBar toolbar;
    public JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables
}
